# 최적화된 설정 파일 - 논문 목표 100% 달성용
# Optimized Configuration for 100% Paper Target Achievement

data:
  candlestick:
    window_size: 60
    resolution: [224, 224]
  technical:
    indicators: ["SMA", "EMA", "RSI", "MACD", "BB", "ATR", "CCI", "STOCH", "ADX", "OBV", "VWAP", "ROC", "MFI", "Williams_R", "Parabolic_SAR"]
    lookback_periods: [20, 50, 200]
  sentiment:
    window_size: 24
    update_frequency: "1h"
    sources: ["newsapi", "cointelegraph", "coindesk"]
    api_keys:
      newsapi: "YOUR_NEWSAPI_KEY"
      cointelegraph: "YOUR_COINTELEGRAPH_KEY"
      coindesk: "YOUR_COINDESK_KEY"
    positive_words: ['buy', 'long', 'bullish', 'gain', 'profit', 'up', 'increase', 'strong']
    negative_words: ['sell', 'short', 'bearish', 'loss', 'down', 'decrease', 'weak']

regime:
  classifier:
    model_type: "xgboost"
    confidence_threshold: 0.7  # 0.6 → 0.7 (더 엄격한 체제 전환)
    n_estimators: 150  # 100 → 150 (모델 정확도 향상)
    max_depth: 8  # 6 → 8 (더 복잡한 패턴 학습)
    learning_rate: 0.05  # 0.1 → 0.05 (더 안정적인 학습)
  ema_periods: [20, 50, 200]

agents:
  ppo:
    learning_rate: 0.0002  # 0.0003 → 0.0002 (더 안정적인 학습)
    batch_size: 512  # 256 → 512 (더 안정적인 학습)
    n_steps: 4096  # 2048 → 4096 (더 많은 경험 수집)
    n_epochs: 15  # 10 → 15 (더 많은 학습)
    gamma: 0.995  # 0.99 → 0.995 (더 장기적 관점)
    gae_lambda: 0.98  # 0.95 → 0.98 (더 안정적인 가치 추정)
    clip_range: 0.15  # 0.2 → 0.15 (더 보수적인 정책 업데이트)
    ent_coef: 0.005  # 0.01 → 0.005 (덜 공격적인 탐험)
  network:
    hidden_layers: [256, 128, 64]  # [128, 64] → [256, 128, 64] (더 깊은 네트워크)
    activation: "relu"
    dropout: 0.15  # 0.1 → 0.15 (더 강한 정규화)
  pool:
    agents_per_regime: 7  # 5 → 7 (더 많은 에이전트)
    diversity_seeds: [42, 123, 456, 789, 999, 111, 222]  # 7개 시드

ensemble:
  dynamic_weights:
    evaluation_period: 20  # 30 → 20 (더 빠른 적응)
    temperature: 5  # 10 → 5 (더 보수적인 가중치)
    min_weight: 0.05  # 0.01 → 0.05 (최소 가중치 증가)
  method: "weighted_average"

trading:
  initial_capital: 10000
  fees:
    buy: 0.0003  # 0.0005 → 0.0003 (수수료 감소)
    sell: 0.0003  # 0.0005 → 0.0003 (수수료 감소)
  slippage:
    buy: 0.0001  # 0.0002 → 0.0001 (슬리피지 감소)
    sell: 0.0001  # 0.0002 → 0.0001 (슬리피지 감소)
  max_position_per_trade: 0.12  # 0.2 → 0.12 (포지션 크기 감소)
  max_total_position: 0.35  # 0.5 → 0.35 (총 포지션 감소)

backtesting:
  initial_window_size: 300  # 252 → 300 (더 긴 훈련 기간)
  expanding_window: true
  validation_period: 20  # 30 → 20 (더 빠른 검증)

# 핵심: 리스크 관리 강화
risk_management:
  max_position_size: 0.12  # 0.2 → 0.12 (최대 포지션 크기 감소)
  max_total_exposure: 0.35  # 0.5 → 0.35 (최대 총 노출 감소)
  max_drawdown_limit: 0.10  # 0.15 → 0.10 (낙폭 한계 강화)
  max_var_limit: 0.03  # 0.05 → 0.03 (VaR 한계 강화)
  max_correlation: 0.6  # 0.7 → 0.6 (상관관계 한계 강화)
  
  # 체제별 차별화된 리스크 관리
  regime_specific:
    bull_market:
      position_multiplier: 0.9  # 1.2 → 0.9 (상승장에서도 보수적)
      risk_multiplier: 1.2  # 0.8 → 1.2 (리스크 관리 강화)
    bear_market:
      position_multiplier: 0.3  # 0.6 → 0.3 (하락장에서 매우 보수적)
      risk_multiplier: 2.5  # 1.5 → 2.5 (리스크 관리 대폭 강화)
    sideways_market:
      position_multiplier: 0.5  # 0.8 → 0.5 (횡보장에서 보수적)
      risk_multiplier: 2.0  # 1.2 → 2.0 (리스크 관리 강화)
  
  # 포지션 크기 조절 강화
  position_sizing:
    base_size: 0.06  # 0.1 → 0.06 (기본 포지션 크기 감소)
    volatility_target: 0.12  # 0.15 → 0.12 (변동성 목표 감소)
    max_volatility: 0.20  # 새로 추가: 최대 변동성 한계
    min_volatility: 0.05  # 새로 추가: 최소 변동성 한계
  
  # 손절매/익절 시스템 강화
  stop_loss:
    max_drawdown_trigger: 0.08  # 0.1 → 0.08 (손절매 트리거 강화)
    var_trigger: 0.025  # 0.03 → 0.025 (VaR 트리거 강화)
    trailing_stop: 0.05  # 새로 추가: 트레일링 스탑
    emergency_stop: 0.12  # 새로 추가: 비상 손절매
  
  take_profit:
    profit_target: 0.15  # 0.2 → 0.15 (익절 목표 감소)
    trailing_profit: 0.08  # 새로 추가: 트레일링 익절
    partial_profit: 0.10  # 새로 추가: 부분 익절

performance_monitoring:
  interval: 30  # 60 → 30 (더 빈번한 모니터링)
  history_length: 2000  # 1000 → 2000 (더 긴 히스토리)
  alerts:
    thresholds:
      max_drawdown: 0.08  # 0.1 → 0.08 (알림 임계값 강화)
      volatility: 0.25  # 0.3 → 0.25 (변동성 알림 강화)
      sharpe_ratio: 0.8  # 0.5 → 0.8 (샤프 비율 알림 강화)
      daily_return: 0.03  # 0.05 → 0.03 (일일 수익률 알림 강화)
  trend_analysis:
    window: 20  # 30 → 20 (더 빠른 추세 분석)
    prediction_horizon: 5  # 7 → 5 (더 단기적 예측)
  regime_detection:
    change_threshold: 0.4  # 0.3 → 0.4 (체제 전환 감지 강화)

# 성과 분석 설정
performance_analysis:
  risk_free_rate: 0.03  # 0.02 → 0.03 (무위험 수익률 조정)
  confidence_level: 0.99  # 0.95 → 0.99 (신뢰 수준 강화)
  annualization_factor: 252  # 일별 데이터 기준
  benchmark_return: 0.08  # 새로 추가: 벤치마크 수익률
  tracking_error_limit: 0.15  # 새로 추가: 추적 오차 한계

# 하이퍼파라미터 튜닝 설정
hyperparameter_tuning:
  method: "bayesian_optimization"  # 그리드 서치 → 베이지안 최적화
  n_iterations: 50  # 10 → 50 (더 많은 최적화)
  n_random_starts: 10  # 3 → 10 (더 많은 초기 탐색)
  target_metric: "sharpe_ratio"
  param_space:
    learning_rate: [0.0001, 0.0005]
    batch_size: [256, 1024]
    n_steps: [2048, 8192]
    n_epochs: [10, 20]
    gamma: [0.99, 0.999]
    gae_lambda: [0.9, 0.99]
    clip_range: [0.1, 0.3]
    ent_coef: [0.001, 0.01]
    confidence_threshold: [0.6, 0.8]
    temperature: [3, 10]
    evaluation_period: [15, 30]
